<!doctype html>
<html lang=en>
  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>Three Students at UR</title>

      <link rel="stylesheet" href="css/styles.css" >
      <link href='https://fonts.googleapis.com/css?family=Expletus+Sans:400' rel='stylesheet' type='text/css'>
      <link href='https://fonts.googleapis.com/css?family=Dosis:400,700' rel='stylesheet' type='text/css'>
  </head>


<body>
  <div class="container">
 

    

